export const ACTION_ADD_TASK = 'ACTION_ADD_TASK'
export const ACTION_DELETE_TASK = 'ACTION_DELETE_TASK'
export const ACTION_CHANGE_CATEGORY = 'ACTION_CHANGE_CATEGORY'

export const ACTION_ACTIVE_TEAM = 'ACTION_ACTIVE_TEAM'
export const ACTION_NON_ACTIVE_TEAM = 'ACTION_NON_ACTIVE_TEAM'

export const ACTION_ACTIVE_USER = 'ACTION_ACTIVE_USER'
